# site
title: Äggie Pak Yee Lee
url: "https://itchyeggie.github.io"
favicon: "/assets/ico.png"

# bio
header: Äggie Pak Yee Lee
desc: >
      李 柏 誼

# posts
prev-next: true

# build settings
markdown: kramdown
kramdown:
  input: GFM
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /:title

plugins:
  - jekyll-seo-tag
